### ISSUE TITLE
All examples not work

### ISSUE THREAD

**Issue by jellybobbin** [Harzu/iced_term#23]
<img width="1340" alt="截屏2024-11-06 18 45 34" src="https://github.com/user-attachments/assets/ac1805ce-4377-4442-9591-89fb5d8a0f43">

Macos 13.6.5

**Comment by Harzu** [comment]
Interesting, I'll fix it. right now you can add `--release` flag and it will work.

**Comment by jellybobbin** [comment]
> Interesting, I'll fix it. right now you can add `--release` flag and it will work.有趣，我会修复它。现在你可以添加`--release`标志，它将起作用。

Yes, it's working...
